server:
  port: 9090
---
spring:
  cloud:
    gateway:
      default-filters:
      - name: HPayGWGlobalFilter
      routes:
        - id: hpay-service1
          uri: http://localhost:9091/
          predicates:
            - Path=/hpay-service1/**
          filters:
          - name: HPayGWPreFilter
          - name: HPayGWPostFilter
        - id: hpay-service2
          uri: http://localhost:9092/
          predicates:
            - Path=/hpay-service2/**